name: DevResourceMonitor
options:
  bundleIdPrefix: com.devresourcemonitor
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "-"
    DEVELOPMENT_TEAM: ""

targets:
  DevResourceMonitor:
    type: application
    platform: macOS
    sources:
      - path: DevResourceMonitor
        excludes:
          - "**/*.xcassets"
    resources:
      - path: DevResourceMonitor/Resources/Assets.xcassets
      - path: DevResourceMonitor/Resources/Info.plist
        buildPhase: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.devresourcemonitor.app
        PRODUCT_NAME: DevResourceMonitor
        INFOPLIST_FILE: DevResourceMonitor/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: DevResourceMonitor/Resources/DevResourceMonitor.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: YES
    entitlements:
      path: DevResourceMonitor/Resources/DevResourceMonitor.entitlements
